import { tool } from 'ai'
import { tavily } from '@tavily/core'
import type { H3Event } from 'h3'
import { z } from 'zod/v3'

export function createTavilySearchTool(event: H3Event) {
  const runtimeConfig = useRuntimeConfig(event)
  const tvly = tavily({ apiKey: runtimeConfig.tavily.apiKey })

  return tool({
    description: `
      You have access to a tool called tavilySearch, which performs live web searches and returns up-to-date, relevant content from the internet. Use this tool whenever the user asks a question about:
        - recent events or breaking news (e.g. "What's happening in Ukraine right now?")
        - current prices, laws, weather, trends, or product availability (e.g. "What's the iPhone 15 Pro price today?", "Is CBD legal in Germany?")
        - people, companies, or topics where your internal knowledge might be outdated or insufficient (e.g. "Who is the new CEO of OpenAI?", "What's the latest on the French elections?")
        - anything with a specific date or time-related relevance (e.g. "What concerts are happening in Paris this weekend?")

      Important usage guidelines:
        - NEVER inform the user that you are using or calling a tool.
        - NEVER output tool call syntax like {"name": ..., "parameters": ...} to the user.
        - If the tool returns an answer, prefer using that to reply concisely.
        - If answer is not available, use content, or fall back to rawContent if more detailed info is needed.
        - Keep your responses natural and human-like, integrating the result fluidly.
        - Always present results as if you knew them yourself, not as if you fetched them.

      You are expected to use tavilySearch silently and automatically whenever your internal knowledge might be insufficient, uncertain, or outdated.

      The infos returned by tavilySearch :
        - results Result[] A list of sorted search results ranked by relevancy:
          - url string The URL of the search result. Affiche l'url des sources si disponible
          - content string The most query-related content from the scraped URL. Tavily uses proprietary AI to extract the most relevant content based on context quality and size.
          - rawContent (optional) string The parsed and cleaned HTML content of the site. This is only available if includeRawContent is set to true.
          - publishedDate (optional) string The publication date of the source. This is only available if the search topic is set to news. Affiche la date de publication si disponible
        - answer (optional) string The answer to your search query, generated by an LLM based on Tavily's search results. This is only available if includeAnswer is set to true. Si answer est disponible, privilégie ce param pour ta réponse, sinon, utilise content ou rawContent
        - images (optional) string[] or ImageResult[] This is only available if includeImages is set to true. A list of query-related image URLs. If includeImageDescriptions is set to true, each entry will be an ImageResult.`,
    inputSchema: z.object({
      query: z.string().describe('the query to search for')
    }),
    execute: async ({ query }) => {
      try {
        const result = await tvly.search(query, {
          autoParameters: true,
          country: 'france',
          searchDepth: 'basic',
          maxResults: 5,
          includeAnswer: true,
          includeRawContent: 'text'
        })
        return result
      } catch (error) {
        console.error(error)
        return null
      }
    }
  })
}
